#!/usr/bin/env bash
# Changes the nginx listening port to 80
apt install -y nginx
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx start
