#!/usr/bin/env bash
# Init script that starts, stops or restarts the manage_my_process subprocess

pid_file=/var/run/my_process.pid

start() {
    ./manage_my_process &
    echo "$!" > "$pid_file"
}

stop() {
    sudo kill -15 "$(cat "$pid_file")" && rm -f "$pid_file"
}

case "$1" in 
    start)
       start
       echo "manage_my_process started"
       ;;
    stop)
       stop
       echo "manage_my_process stopped"
       ;;
    restart)
       stop
       start
       echo "manage_my_process restarted"
       ;;
    *)
       echo "Usage: manage_my_process {start|stop|restart}"
esac

exit 0
